version: "3.0"

services:
    db:
        container_name: db
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: reskinner
            POSTGRES_PASSWORD: reskinner
            POSTGRES_DB: reskinner

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8081:8080
        depends_on:
            - db

    reskinner:
        container_name: reskinner
        image: reskinner
        build: .
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
